# Copyright 2026 Canonical Ltd.
# See LICENSE file for licensing details.

name: Terraform modules release
on:
  workflow_dispatch:
  pull_request:
    paths:
      - "terraform/**"
  push:
    branches:
      - main
    paths:
      - "terraform/**"

jobs:
  terraform:
    uses: f-atwi/operator-workflows/.github/workflows/terraform_modules_release.yaml@main
    permissions:
      contents: write
    with:
      compliance-only: ${{ github.event_name == 'pull_request' }}
      terraform-directories: '["terraform/product", "terraform/modules/gateway-api-integrator"]'
    secrets: inherit
